/* Codded by @phaticusthiccy
Telegram: t.me/phaticusthiccy
Instagram: www.instagram.com/kyrie.baran
*/

const Asena = require('../events');
const {MessageType,Mimetype} = require('@adiwajshing/baileys');
const fs = require('fs');
const {execFile} = require('child_process');
const cwebp = require('cwebp-bin');
const Config = require('../config');
const exec = require('child_process').exec;
const Language = require('../language');
const Lang = Language.getString('conventer');

if (Config.WORKTYPE == 'private') {

    Asena.addCommand({pattern: 'effectpro$', fromMe: true, desc: Lang.XMEDİA_DESC}, (async (message, match) => {    
        if (Config.LANG == 'EN' || Config.LANG == 'HI') {
            await message.sendMessage('*◁WhatsAlexa Logo Panel▷*\n\n*🧞‍♀️විධානය* : .zwolf\n*💠example* : ```Whats/Alexa```\n\n*🧞‍♀️විධානය* : .wfire\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .shadow\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .smoke\n*💠example* : ```Whatsalexa```\n\n*🌀විධානය* : .dropwater\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .glitch\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .harrypotter\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .beach\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .8bit\n*💠විස්තරය* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .naruto\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .clight\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .marvel\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .studiomarvel\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .cloud\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .snow\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .blood\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .blackpink\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* :  .battlefield\n*💠example* : ``` Whats/Alexa```\n\n*🧞‍♀️විධානය* :  .wolfmetal\n*💠විස්තරය* : ``` Whats/alexa```\n\n*🧞‍♀️විධානය* : .aov\n*💠example* : ```.aov Whatsalexa```\n\n*🧞‍♀️විධානය* : .csgo\n*💠example* : ```.csgo whatsalexa```\n\n*🧞‍♀️විධානය* : .lolavatar\n*💠example* : ```.lolavatar whatsalexa```\n\n*🧞‍♀️විධානය* : .gavatar\n*💠example* : ```.gavatar whatsalexa```\n\n*🧞‍♀️විධානය* : .neon\n*💠example* : ```.neon whatsalexa```\n\n*🧞‍♀️විධානය* : .galaxyneon\n*💠example* : ```.galaxyneon whatsalexa```\n\n*🧞‍♀️විධානය* : .glue\n*💠example* : ```.glue whatsalexa```\n\n*🧞‍♀️විධානය* : .graved\n*💠විස්තරය* : ```.graved whatsalexa```\n\n*🧞‍♀️විධානය* : .vintage\n*💠example* : ```.vintage whatsalexa```\n\n*🧞‍♀️විධානය* : .metald\n*💠example* : ```.metald whatsalexa```\n\n*🧞‍♀️විධානය* : .sparkling\n*💠විස්තරය* : ```.sparkling whats/alexa```\n\n*🧞‍♀️විධානය* : .flower\n*💠විස්තරය* : ```.flower whatsalexa```\n\n*🌎Developer - SISULAWELGAMAGE*');
        } else { 
            await message.sendMessage('*◁WhatsAlexa Logo Panel▷*\n\n*🧞‍♀️විධානය* : .zwolf\n*💠example* : ```Whats/Alexa```\n\n*🧞‍♀️විධානය* : .wfire\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .shadow\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .smoke\n*💠example* : ```Whatsalexa```\n\n*🌀විධානය* : .dropwater\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .glitch\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .harrypotter\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .beach\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .8bit\n*💠විස්තරය* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .naruto\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .clight\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .marvel\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .studiomarvel\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .cloud\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .snow\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .blood\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .blackpink\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* :  .battlefield\n*💠example* : ``` Whats/Alexa```\n\n*🧞‍♀️විධානය* :  .wolfmetal\n*💠විස්තරය* : ``` Whats/alexa```\n\n*🧞‍♀️විධානය* : .aov\n*💠example* : ```.aov Whatsalexa```\n\n*🧞‍♀️විධානය* : .csgo\n*💠example* : ```.csgo whatsalexa```\n\n*🧞‍♀️විධානය* : .lolavatar\n*💠example* : ```.lolavatar whatsalexa```\n\n*🧞‍♀️විධානය* : .gavatar\n*💠example* : ```.gavatar whatsalexa```\n\n*🧞‍♀️විධානය* : .neon\n*💠example* : ```.neon whatsalexa```\n\n*🧞‍♀️විධානය* : .galaxyneon\n*💠example* : ```.galaxyneon whatsalexa```\n\n*🧞‍♀️විධානය* : .glue\n*💠example* : ```.glue whatsalexa```\n\n*🧞‍♀️විධානය* : .graved\n*💠විස්තරය* : ```.graved whatsalexa```\n\n*🧞‍♀️විධානය* : .vintage\n*💠example* : ```.vintage whatsalexa```\n\n*🧞‍♀️විධානය* : .metald\n*💠example* : ```.metald whatsalexa```\n\n*🧞‍♀️විධානය* : .sparkling\n*💠විස්තරය* : ```.sparkling whats/alexa```\n\n*🧞‍♀️විධානය* : .flower\n*💠විස්තරය* : ```.flower whatsalexa```\n\n*🌎Developer - SISULAWELGAMAGE*');
        }
    }));
}

if (Config.WORKTYPE == 'public') {

    Asena.addCommand({pattern: 'effectpro$', fromMe: false, desc: Lang.XMEDİA_DESC}, (async (message, match) => {    
        if (Config.LANG == 'EN' || Config.LANG == 'HI') {
            await message.sendMessage('*◁WhatsAlexa Logo Panel▷*\n\n*🧞‍♀️විධානය* : .zwolf\n*💠example* : ```Whats/Alexa```\n\n*🧞‍♀️විධානය* : .wfire\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .shadow\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .smoke\n*💠example* : ```Whatsalexa```\n\n*🌀විධානය* : .dropwater\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .glitch\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .harrypotter\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .beach\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .8bit\n*💠විස්තරය* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .naruto\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .clight\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .marvel\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .studiomarvel\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .cloud\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .snow\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .blood\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .blackpink\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* :  .battlefield\n*💠example* : ``` Whats/Alexa```\n\n*🧞‍♀️විධානය* :  .wolfmetal\n*💠විස්තරය* : ``` Whats/alexa```\n\n*🧞‍♀️විධානය* : .aov\n*💠example* : ```.aov Whatsalexa```\n\n*🧞‍♀️විධානය* : .csgo\n*💠example* : ```.csgo whatsalexa```\n\n*🧞‍♀️විධානය* : .lolavatar\n*💠example* : ```.lolavatar whatsalexa```\n\n*🧞‍♀️විධානය* : .gavatar\n*💠example* : ```.gavatar whatsalexa```\n\n*🧞‍♀️විධානය* : .neon\n*💠example* : ```.neon whatsalexa```\n\n*🧞‍♀️විධානය* : .galaxyneon\n*💠example* : ```.galaxyneon whatsalexa```\n\n*🧞‍♀️විධානය* : .glue\n*💠example* : ```.glue whatsalexa```\n\n*🧞‍♀️විධානය* : .graved\n*💠විස්තරය* : ```.graved whatsalexa```\n\n*🧞‍♀️විධානය* : .vintage\n*💠example* : ```.vintage whatsalexa```\n\n*🧞‍♀️විධානය* : .metald\n*💠example* : ```.metald whatsalexa```\n\n*🧞‍♀️විධානය* : .sparkling\n*💠විස්තරය* : ```.sparkling whats/alexa```\n\n*🧞‍♀️විධානය* : .flower\n*💠විස්තරය* : ```.flower whatsalexa```\n\n*🌎Developer - SISULAWELGAMAGE*');
        } else { 
            await message.sendMessage('*◁WhatsAlexa Logo Panel▷*\n\n*🧞‍♀️විධානය* : .zwolf\n*💠example* : ```Whats/Alexa```\n\n*🧞‍♀️විධානය* : .wfire\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .shadow\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .smoke\n*💠example* : ```Whatsalexa```\n\n*🌀විධානය* : .dropwater\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .glitch\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .harrypotter\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .beach\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .8bit\n*💠විස්තරය* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .naruto\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .clight\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .marvel\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .studiomarvel\n*💠example* : ```Whats/alexa```\n\n*🧞‍♀️විධානය* : .cloud\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .snow\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* : .blood\n*💠example* : ```WhatsAlexa```\n\n*🧞‍♀️විධානය* : .blackpink\n*💠example* : ```Whatsalexa```\n\n*🧞‍♀️විධානය* :  .battlefield\n*💠example* : ``` Whats/Alexa```\n\n*🧞‍♀️විධානය* :  .wolfmetal\n*💠විස්තරය* : ``` Whats/alexa```\n\n*🧞‍♀️විධානය* : .aov\n*💠example* : ```.aov Whatsalexa```\n\n*🧞‍♀️විධානය* : .csgo\n*💠example* : ```.csgo whatsalexa```\n\n*🧞‍♀️විධානය* : .lolavatar\n*💠example* : ```.lolavatar whatsalexa```\n\n*🧞‍♀️විධානය* : .gavatar\n*💠example* : ```.gavatar whatsalexa```\n\n*🧞‍♀️විධානය* : .neon\n*💠example* : ```.neon whatsalexa```\n\n*🧞‍♀️විධානය* : .galaxyneon\n*💠example* : ```.galaxyneon whatsalexa```\n\n*🧞‍♀️විධානය* : .glue\n*💠example* : ```.glue whatsalexa```\n\n*🧞‍♀️විධානය* : .graved\n*💠විස්තරය* : ```.graved whatsalexa```\n\n*🧞‍♀️විධානය* : .vintage\n*💠example* : ```.vintage whatsalexa```\n\n*🧞‍♀️විධානය* : .metald\n*💠example* : ```.metald whatsalexa```\n\n*🧞‍♀️විධානය* : .sparkling\n*💠විස්තරය* : ```.sparkling whats/alexa```\n\n*🧞‍♀️විධානය* : .flower\n*💠විස්තරය* : ```.flower whatsalexa```\n\n*🌎Developer - SISULAWELGAMAGE*');
        }
    }));
}
